files_colomn = {
    'allergies.csv': ['START','STOP','PATIENT','ENCOUNTER','CODE','SYSTEM','DESCRIPTION','TYPE','CATEGORY',	'REACTION1','DESCRIPTION1','SEVERITY1','REACTION2','DESCRIPTION2','SEVERITY2'],
    'patients.csv': ['PATIENT','BIRTHDATE','DEATHDATE','RACE','GENDER'],
    'claims.csv': ['PATIENT','DIAGNOSIS1','DIAGNOSIS2','DIAGNOSIS3','DIAGNOSIS4','DIAGNOSIS5','DIAGNOSIS6','DIAGNOSIS7','DIAGNOSIS8','CURRENTILLNESSDATE','ENCOUNTER'],
    'encounters.csv': ['ENCOUNTER','START','STOP','PATIENT','ENCOUNTERCLASS','CODE','DESCRIPTION','REASONCODE','REASONDESCRIPTION'],
    'careplans.csv': ['START','STOP','PATIENT','ENCOUNTER','CODE','DESCRIPTION','REASONCODE','REASONDESCRIPTION'],
    'conditions.csv': ['START','STOP','PATIENT','ENCOUNTER','CODE','DESCRIPTION'],
    'observations.csv': ['PATIENT','ENCOUNTER','DESCRIPTION','VALUE','UNITS'],
    'procedures.csv': ['PATIENT','ENCOUNTER','CODE','DESCRIPTION'],
    'imaging_studies.csv': ['PATIENT','ENCOUNTER','BODYSITE_CODE','BODYSITE_DESCRIPTION','MODALITY_DESCRIPTION','PROCEDURE_CODE'],
    'supplies.csv': ['PATIENT','ENCOUNTER','CODE','DESCRIPTION'],
    'devices.csv':['PATIENT','ENCOUNTER','CODE','DESCRIPTION'],
    'immunizations.csv':['PATIENT','ENCOUNTER','CODE','DESCRIPTION'],
    'medications.csv':['PATIENT','ENCOUNTER','REASONCODE','DESCRIPTION','REASONDESCRIPTION']
}